server:
  port: 8092
  servlet:
    context-path: /sds/location/api/

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show_sql: true
  datasource:
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:LOCATION}
  application:
    name: SDS-Location

  flyway:
    baselineOnMigrate: true
    locations: classpath:db
    schemas: public
    enabled: true
    validate-on-migrate: true

  springdoc:
    swagger-ui:
      doc-expansion: none
